name: gamepads_darwin
publish_to: none
description: MacOS implementation of gamepads, a Flutter plugin to handle gamepad input across multiple platforms.
version: 0.1.2+4
homepage: https://github.com/yj-labs/gamepads
repository: https://github.com/yj-labs/gamepads

flutter:
  plugin:
    implements: gamepads
    platforms:
      macos:
        pluginClass: GamepadsDarwinPlugin

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  gamepads_platform_interface:
    git:
      url: https://github.com/yj-labs/gamepads.git
      ref: dev
      path: packages/gamepads_platform_interface

dev_dependencies:
  flame_lint: ^1.4.1
  flutter_test:
    sdk: flutter
